import { Router, Request, Response } from 'express';
import { query, queryOne, transaction } from '../db/index.js';
import { authenticate, requireHR } from '../middleware/auth.js';
import { Candidate } from '../types/index.js';

const router = Router();
router.use(authenticate);

// IDs auto-generated by PostgreSQL sequences

// ─── GET /api/candidates — search across all candidates ──────────────────────
router.get('/', async (req: Request, res: Response) => {
  const { q, skills, industry, status, tag, limit = '50', offset = '0' } = req.query;

  let sql = `
    SELECT c.*,
      json_agg(json_build_object(
        'id', a.id, 'role_id', a.role_id, 'role_title', r.title,
        'stage', a.stage, 'status', a.status, 'ai_fit_score', a.ai_fit_score
      ) ORDER BY a.application_date DESC) FILTER (WHERE a.id IS NOT NULL) AS applications
    FROM candidates c
    LEFT JOIN applications a ON a.candidate_id = c.id
    LEFT JOIN roles r ON r.id = a.role_id
    WHERE 1=1
  `;
  const params: unknown[] = [];
  let i = 1;

  if (q) {
    sql += ` AND (c.full_name ILIKE $${i} OR c.email ILIKE $${i} OR c.phone ILIKE $${i})`;
    params.push(`%${q}%`); i++;
  }
  if (skills) {
    sql += ` AND c.parsed_skills && $${i++}::text[]`;
    params.push(Array.isArray(skills) ? skills : [skills]);
  }
  if (industry) {
    sql += ` AND $${i++} = ANY(c.parsed_industries)`;
    params.push(industry);
  }
  if (tag) {
    sql += ` AND $${i++} = ANY(c.hr_tags)`;
    params.push(tag);
  }

  sql += ` GROUP BY c.id ORDER BY c.updated_at DESC LIMIT $${i++} OFFSET $${i++}`;
  params.push(parseInt(limit as string), parseInt(offset as string));

  const candidates = await query<Candidate>(sql, params);

  const countSql = sql.replace(/SELECT c\.\*[\s\S]+?FROM/, 'SELECT COUNT(*) FROM').replace(/GROUP BY[\s\S]+$/, '');
  const countResult = await queryOne<{ count: string }>(countSql.split('LIMIT')[0], params.slice(0, -2));
  const total = parseInt(countResult?.count || '0');

  res.json({ candidates, total, limit: parseInt(limit as string), offset: parseInt(offset as string) });
});

// ─── GET /api/candidates/:id ──────────────────────────────────────────────────
router.get('/:id', async (req: Request, res: Response) => {
  const candidate = await queryOne<Candidate>(
    'SELECT * FROM candidates WHERE id = $1',
    [req.params.id]
  );
  if (!candidate) { res.status(404).json({ error: 'Candidate not found' }); return; }

  // Fetch all applications for this candidate
  const applications = await query(
    `SELECT a.*, r.title AS role_title, ag.name AS agency_name
     FROM applications a
     JOIN roles r ON r.id = a.role_id
     LEFT JOIN agencies ag ON ag.id = a.agency_id
     WHERE a.candidate_id = $1
     ORDER BY a.application_date DESC`,
    [req.params.id]
  );

  res.json({ candidate, applications });
});

// ─── POST /api/candidates — create candidate + optional application ───────────
router.post('/', requireHR, async (req: Request, res: Response) => {
  const {
    full_name, email, phone, linkedin_url, role_id, source_channel, agency_id,
    current_ctc_fixed, current_ctc_variable, current_esops, expected_ctc,
    notice_period_days, current_company, current_industry, current_designation,
    current_location, years_of_experience, resume_drive_link,
  } = req.body;

  if (!full_name) { res.status(400).json({ error: 'full_name required' }); return; }

  // Duplicate check: email
  if (email) {
    const existing = await queryOne<Candidate>(
      'SELECT id, full_name FROM candidates WHERE email = $1',
      [email.toLowerCase()]
    );
    if (existing) {
      res.status(409).json({
        error: 'Duplicate email',
        existing_id: existing.id,
        existing_name: existing.full_name,
        message: 'A candidate with this email already exists. Use their existing profile or confirm this is a different person.',
      });
      return;
    }
  }

  const result = await transaction(async (client) => {
    const cand = await client.query(
      `INSERT INTO candidates (
         full_name, email, phone, linkedin_url,
         current_ctc_fixed, current_ctc_variable, current_esops, expected_ctc,
         notice_period_days, current_company, current_industry, current_designation,
         current_location, years_of_experience, resume_drive_link
       )
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,
      [
        full_name, email?.toLowerCase(), phone, linkedin_url,
        current_ctc_fixed ?? null, current_ctc_variable ?? null, current_esops ?? null, expected_ctc ?? null,
        notice_period_days ?? null, current_company ?? null, current_industry ?? null, current_designation ?? null,
        current_location ?? null, years_of_experience ?? null, resume_drive_link ?? null,
      ]
    );
    const candidate = cand.rows[0] as Candidate;

    let application = null;
    if (role_id) {
      const app = await client.query(
        `INSERT INTO applications (candidate_id, role_id, source_channel, agency_id,
           stage, status, recruiter_screening_status, stage_entry_time, sla_hours)
         VALUES ($1,$2,$3,$4,'Applied','Active','New',NOW(),48) RETURNING *`,
        [candidate.id, role_id, source_channel, agency_id || null]
      );
      application = app.rows[0];

      // Log to activity log
      await client.query(
        `INSERT INTO activity_log (application_id, candidate_id, role_id, event_type, event_detail, new_value, performed_by, performed_by_name)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
        [application.id, candidate.id, role_id, 'Application Created', 'New application created',
         JSON.stringify({ stage: 'Applied', source: source_channel }),
         req.user!.userId, req.user!.name]
      );
    }

    return { candidate, application };
  });

  res.status(201).json(result);
});

// ─── POST /api/candidates/:id/applications — link an existing candidate to a
// role. Fills the gap the manual POST / above can't: that route is
// create-only for the candidate (409s on a duplicate email), so it can't be
// reused for someone who already exists — e.g. a candidate ingested via the
// Job Application Form whose "role applying for" answer didn't match any
// open role (candidateIngest.ts's Unmatched Role — Manual Reconciliation
// path) and needs linking by hand. ────────────────────────────────────────────
router.post('/:id/applications', requireHR, async (req: Request, res: Response) => {
  const { role_id, source_channel } = req.body;

  const candidate = await queryOne<Candidate>('SELECT id FROM candidates WHERE id = $1', [req.params.id]);
  if (!candidate) { res.status(404).json({ error: 'Candidate not found' }); return; }

  if (!role_id) { res.status(400).json({ error: 'role_id is required' }); return; }
  const role = await queryOne<{ id: string }>('SELECT id FROM roles WHERE id = $1', [role_id]);
  if (!role) { res.status(400).json({ error: 'Role not found' }); return; }

  const existingApp = await queryOne<{ id: string }>(
    'SELECT id FROM applications WHERE candidate_id = $1 AND role_id = $2',
    [req.params.id, role_id]
  );
  if (existingApp) {
    res.status(409).json({ error: 'Already linked to this role', application_id: existingApp.id });
    return;
  }

  const application = await transaction(async (client) => {
    const appResult = await client.query(
      `INSERT INTO applications (
         candidate_id, role_id, source_channel,
         stage, status, recruiter_screening_status, stage_entry_time, sla_hours
       ) VALUES ($1,$2,$3,'Applied','Active','New',NOW(),48) RETURNING *`,
      [req.params.id, role_id, source_channel || null]
    );
    const app = appResult.rows[0];

    await client.query(
      `INSERT INTO activity_log (application_id, candidate_id, role_id, event_type, event_detail, new_value, performed_by, performed_by_name)
       VALUES ($1,$2,$3,'Application Created','Application manually linked from unmatched-role reconciliation',$4,$5,$6)`,
      [app.id, req.params.id, role_id, JSON.stringify({ stage: 'Applied', source: source_channel }), req.user!.userId, req.user!.name]
    );

    return app;
  });

  res.status(201).json({ application });
});

// ─── PATCH /api/candidates/:id — update profile fields, with edit log ────────
router.patch('/:id', requireHR, async (req: Request, res: Response) => {
  const existing = await queryOne<Candidate>('SELECT * FROM candidates WHERE id = $1', [req.params.id]);
  if (!existing) { res.status(404).json({ error: 'Candidate not found' }); return; }

  const allowedFields = [
    'full_name','email','phone','linkedin_url','parsed_total_yoe',
    'parsed_skills','parsed_industries','parsed_education','job_stability_months',
    'career_progression','parsing_completeness','hr_tags','duplicate_flag',
    'current_ctc_fixed','current_ctc_variable','current_esops','expected_ctc',
    'notice_period_days','current_company','current_industry','current_designation',
    'current_location','years_of_experience','resume_drive_link',
  ];

  const updates: string[] = [];
  const values: unknown[] = [];
  const editLogEntries: Array<{ field: string; old: string; new_val: string }> = [];
  let idx = 1;

  for (const field of allowedFields) {
    if (req.body[field] !== undefined) {
      const oldVal = String((existing as Record<string, unknown>)[field] ?? '');
      const newVal = String(req.body[field]);
      if (oldVal !== newVal) {
        updates.push(`${field} = $${idx++}`);
        values.push(req.body[field]);
        editLogEntries.push({ field, old: oldVal, new_val: newVal });
      }
    }
  }

  if (updates.length === 0) {
    res.json({ candidate: existing, message: 'No changes detected' });
    return;
  }

  values.push(req.params.id);
  const candidate = await transaction(async (client) => {
    const result = await client.query(
      `UPDATE candidates SET ${updates.join(', ')} WHERE id = $${idx} RETURNING *`,
      values
    );

    for (const entry of editLogEntries) {
      await client.query(
        `INSERT INTO candidate_edit_log (candidate_id, field_name, old_value, new_value, changed_by)
         VALUES ($1, $2, $3, $4, $5)`,
        [req.params.id, entry.field, entry.old, entry.new_val, req.user!.userId]
      );
    }

    return result.rows[0] as Candidate;
  });

  res.json({ candidate });
});

// ─── GET /api/candidates/:id/edit-log ─────────────────────────────────────────
router.get('/:id/edit-log', async (req: Request, res: Response) => {
  const logs = await query(
    `SELECT el.*, u.name AS changed_by_name
     FROM candidate_edit_log el
     LEFT JOIN users u ON u.id = el.changed_by
     WHERE el.candidate_id = $1
     ORDER BY el.changed_at DESC`,
    [req.params.id]
  );
  res.json({ logs });
});

// ─── GET /api/candidates/:id/activity — full activity timeline ────────────────
router.get('/:id/activity', async (req: Request, res: Response) => {
  const log = await query(
    `SELECT al.*, u.name AS performed_by_name, r.title AS role_title
     FROM activity_log al
     LEFT JOIN users u ON u.id = al.performed_by
     LEFT JOIN roles r ON r.id = al.role_id
     WHERE al.candidate_id = $1
     ORDER BY al.created_at DESC`,
    [req.params.id]
  );
  res.json({ activity: log });
});

export default router;
