import { Router, Request, Response } from 'express';
import { query, queryOne, transaction } from '../db/index.js';
import { authenticate, requireHR, stripRestrictedFields } from '../middleware/auth.js';
import { Candidate } from '../types/index.js';
import { parseRoleFilters, buildRoleFilterSql, hasActiveFilters } from '../utils/roleFilters.js';
import { isSeverelyOverBudget } from '../utils/budget.js';

const router = Router();
router.use(authenticate);

// IDs auto-generated by PostgreSQL sequences

// ─── GET /api/candidates — search across all candidates ──────────────────────
router.get('/', async (req: Request, res: Response) => {
  const { q, skills, industry, tag, hold_for_future, archived, unlinked, limit = '50', offset = '0' } = req.query;

  let sql = `
    SELECT c.*,
      json_agg(json_build_object(
        'id', a.id, 'role_id', a.role_id, 'role_title', r.title,
        'stage', a.stage, 'status', a.status, 'ai_fit_score', a.ai_fit_score,
        'last_updated', a.last_updated
      ) ORDER BY a.application_date DESC) FILTER (WHERE a.id IS NOT NULL) AS applications
    FROM candidates c
    LEFT JOIN applications a ON a.candidate_id = c.id
    LEFT JOIN roles r ON r.id = a.role_id
    WHERE 1=1
  `;
  const params: unknown[] = [];
  let i = 1;

  if (q) {
    sql += ` AND (c.full_name ILIKE $${i} OR c.email ILIKE $${i} OR c.phone ILIKE $${i})`;
    params.push(`%${q}%`); i++;
  }
  if (skills) {
    sql += ` AND c.parsed_skills && $${i++}::text[]`;
    params.push(Array.isArray(skills) ? skills : [skills]);
  }
  if (industry) {
    sql += ` AND $${i++} = ANY(c.parsed_industries)`;
    params.push(industry);
  }
  if (tag) {
    sql += ` AND $${i++} = ANY(c.hr_tags)`;
    params.push(tag);
  }
  // Talent Pool / Archival (PRD §21) — the PRD's own suggested query
  // (?tag=Hold+for+Future) doesn't actually work: nothing auto-tags hr_tags
  // when an application's status changes. status lives on applications,
  // not candidates, so these are EXISTS filters rather than a plain column
  // match. No $n param needed — nothing user-controlled enters the SQL
  // fragment itself, only the fixed 'true' string check gates whether the
  // literal clause (with no interpolated values) gets appended at all.
  if (hold_for_future === 'true') {
    sql += ` AND EXISTS (SELECT 1 FROM applications a2 WHERE a2.candidate_id = c.id AND a2.status = 'Hold for Future')`;
  }
  if (archived === 'true') {
    sql += ` AND EXISTS (SELECT 1 FROM applications a2 WHERE a2.candidate_id = c.id AND a2.status IN ('Rejected','Withdrawn'))`;
  }
  // Candidates.tsx's "Unlinked candidates" panel used to fetch a flat
  // limit:100 page and filter client-side to applications == null — so a
  // candidate with zero applications only showed up if they happened to
  // fall within the 100 most-recently-updated candidates overall. This
  // filters at the query level instead, so the panel can page through the
  // real, complete set.
  if (unlinked === 'true') {
    sql += ` AND NOT EXISTS (SELECT 1 FROM applications a2 WHERE a2.candidate_id = c.id)`;
  }

  // Talent Pool's Department/Location/Role master filters — "does this
  // candidate have at least one application against a role matching these"
  // rather than a plain join+WHERE, for the same reason as hold_for_future/
  // archived above: this query's own LEFT JOIN roles r is there to build the
  // per-candidate applications array via json_agg, and filtering that join
  // directly would silently drop non-matching applications from the array
  // instead of excluding non-matching candidates. Reuses roleFilters.ts's
  // r-aliased SQL fragment as-is inside this subquery's own roles join.
  const roleFilters = parseRoleFilters(req.query);
  if (hasActiveFilters(roleFilters)) {
    const { sql: roleFilterSql, params: roleFilterParams } = buildRoleFilterSql(roleFilters, i);
    sql += ` AND EXISTS (SELECT 1 FROM applications a2 JOIN roles r ON r.id = a2.role_id WHERE a2.candidate_id = c.id${roleFilterSql})`;
    params.push(...roleFilterParams);
    i += roleFilterParams.length;
  }

  // c.updated_at only moves on candidate PROFILE edits, not on an
  // application's status changing — without this, a candidate archived
  // five minutes ago wouldn't sort anywhere near the top of either pool.
  let orderBy = 'c.updated_at DESC';
  if (hold_for_future === 'true') {
    orderBy = `(SELECT MAX(a2.last_updated) FROM applications a2 WHERE a2.candidate_id = c.id AND a2.status = 'Hold for Future') DESC NULLS LAST`;
  } else if (archived === 'true') {
    orderBy = `(SELECT MAX(a2.last_updated) FROM applications a2 WHERE a2.candidate_id = c.id AND a2.status IN ('Rejected','Withdrawn')) DESC NULLS LAST`;
  }

  sql += ` GROUP BY c.id ORDER BY ${orderBy} LIMIT $${i++} OFFSET $${i++}`;
  params.push(parseInt(limit as string), parseInt(offset as string));

  const candidates = await query<Candidate>(sql, params);

  // COUNT(DISTINCT c.id), not COUNT(*) — the LEFT JOIN to applications fans
  // out one row per application, so a plain COUNT(*) over-counts any
  // candidate with more than one application (exactly the case the Talent
  // Pool's cross-role-history filters are built around). Pre-existing bug,
  // caught while verifying the new hold_for_future/archived filters against
  // a candidate with 2 applications — total was silently wrong before this.
  const countSql = sql.replace(/SELECT c\.\*[\s\S]+?FROM/, 'SELECT COUNT(DISTINCT c.id) FROM').replace(/GROUP BY[\s\S]+$/, '');
  const countResult = await queryOne<{ count: string }>(countSql.split('LIMIT')[0], params.slice(0, -2));
  const total = parseInt(countResult?.count || '0');

  res.json({ candidates, total, limit: parseInt(limit as string), offset: parseInt(offset as string) });
});

// ─── GET /api/candidates/unmatched-role-submissions ────────────────────────────
// Must be registered before GET /:id (Express would otherwise match this path
// as an :id value). Surfaces every Job Application Form submission whose
// role text never matched a role — the only other trace of these today is a
// buried 'Unmatched Role — Manual Reconciliation' activity_log entry on the
// candidate's own record, invisible unless you already knew to look (and,
// for a candidate who already has an application to some OTHER role, they
// don't even show up in the Unlinked Candidates panel, so this was the one
// case with no visibility anywhere). Resolved live, with no separate
// "mark resolved" flag: DISTINCT ON collapses repeat submissions of the same
// text down to the latest attempt, a live re-match against current role
// titles powers the one-click "suggested role" (catches cases like a role
// created after the candidate applied, or a title/dropdown text mismatch
// that's since been fixed), and the NOT EXISTS clause drops a row the moment
// a real application exists for that suggested role — whether created from
// this panel or any other way (e.g. the Add Application button).
router.get('/unmatched-role-submissions', requireHR, async (req: Request, res: Response) => {
  const { limit = '50', offset = '0' } = req.query;

  const baseCte = `
    WITH latest AS (
      SELECT DISTINCT ON (al.candidate_id, al.event_detail)
        al.candidate_id, c.full_name, c.email, al.event_detail AS submitted_text, al.created_at,
        (SELECT r.id FROM roles r
           WHERE lower(regexp_replace(translate(trim(r.title), '–—', '--'), '\\s+', ' ', 'g'))
               = lower(regexp_replace(translate(trim(al.event_detail), '–—', '--'), '\\s+', ' ', 'g'))
             AND r.status NOT IN ('Closed – Filled', 'Closed – Cancelled')
           LIMIT 1) AS suggested_role_id,
        (SELECT r.title FROM roles r
           WHERE lower(regexp_replace(translate(trim(r.title), '–—', '--'), '\\s+', ' ', 'g'))
               = lower(regexp_replace(translate(trim(al.event_detail), '–—', '--'), '\\s+', ' ', 'g'))
             AND r.status NOT IN ('Closed – Filled', 'Closed – Cancelled')
           LIMIT 1) AS suggested_role_title
      FROM activity_log al
      JOIN candidates c ON c.id = al.candidate_id
      WHERE al.event_type = 'Unmatched Role — Manual Reconciliation'
      ORDER BY al.candidate_id, al.event_detail, al.created_at DESC
    )
    SELECT * FROM latest l
    WHERE NOT EXISTS (
      SELECT 1 FROM applications a2 WHERE a2.candidate_id = l.candidate_id AND a2.role_id = l.suggested_role_id
    )
  `;

  const rows = await query<{
    candidate_id: string; full_name: string; email: string | null; submitted_text: string;
    created_at: string; suggested_role_id: string | null; suggested_role_title: string | null;
  }>(`${baseCte} ORDER BY created_at DESC LIMIT $1 OFFSET $2`, [parseInt(limit as string), parseInt(offset as string)]);

  const countResult = await queryOne<{ count: string }>(`SELECT COUNT(*) FROM (${baseCte}) c`);
  const total = parseInt(countResult?.count || '0');

  res.json({ submissions: rows, total, limit: parseInt(limit as string), offset: parseInt(offset as string) });
});

// ─── GET /api/candidates/:id ──────────────────────────────────────────────────
router.get('/:id', async (req: Request, res: Response) => {
  const candidate = await queryOne<Candidate>(
    'SELECT * FROM candidates WHERE id = $1',
    [req.params.id]
  );
  if (!candidate) { res.status(404).json({ error: 'Candidate not found' }); return; }

  // Fetch all applications for this candidate
  const applications = await query(
    `SELECT a.*, r.title AS role_title, r.ctc_band AS role_ctc_band, ag.name AS agency_name
     FROM applications a
     JOIN roles r ON r.id = a.role_id
     LEFT JOIN agencies ag ON ag.id = a.agency_id
     WHERE a.candidate_id = $1
     ORDER BY a.application_date DESC`,
    [req.params.id]
  );

  // This route never stripped restricted fields before — a.* included
  // internal_risk_notes/offer_ctc_fixed/offer_ctc_variable/hr_comp_alignment/
  // agency_fee_estimate unfiltered for every persona (the frontend just
  // never rendered them for non-HR, which isn't a real boundary). Fixed
  // here as a direct consequence of adding role_ctc_band, itself restricted.
  const persona = req.user!.persona;
  // is_severely_over_budget computed here too — this route has its own
  // separate applications query (distinct from GET /api/applications and
  // GET /api/applications/:id, which already do this), so it needed the
  // exact same fix independently: CandidateDetail.tsx's Stage-change modal
  // reads applications from THIS endpoint, and without this field present
  // here the mandatory over-budget reason gate silently never triggered for
  // any persona using this page's Stage control specifically.
  const safeApplications = applications.map(a => {
    const row = a as unknown as Record<string, unknown> & { role_ctc_band?: string };
    const isSeverelyOver = isSeverelyOverBudget(candidate.expected_ctc, row.role_ctc_band);
    return { ...stripRestrictedFields(row, persona), is_severely_over_budget: isSeverelyOver };
  });

  res.json({ candidate, applications: safeApplications });
});

// ─── POST /api/candidates — create candidate + optional application ───────────
router.post('/', requireHR, async (req: Request, res: Response) => {
  const {
    full_name, email, phone, linkedin_url, role_id, source_channel, agency_id,
    current_ctc_fixed, current_ctc_variable, current_esops, expected_ctc,
    notice_period_days, current_company, current_industry, current_designation,
    current_location, years_of_experience, resume_drive_link, languages_known,
    preferred_location,
  } = req.body;

  if (!full_name) { res.status(400).json({ error: 'full_name required' }); return; }

  // Duplicate check: email
  if (email) {
    const existing = await queryOne<Candidate>(
      'SELECT id, full_name FROM candidates WHERE email = $1',
      [email.toLowerCase()]
    );
    if (existing) {
      res.status(409).json({
        error: 'Duplicate email',
        existing_id: existing.id,
        existing_name: existing.full_name,
        message: 'A candidate with this email already exists. Use their existing profile or confirm this is a different person.',
      });
      return;
    }
  }

  const result = await transaction(async (client) => {
    const cand = await client.query(
      `INSERT INTO candidates (
         full_name, email, phone, linkedin_url,
         current_ctc_fixed, current_ctc_variable, current_esops, expected_ctc,
         notice_period_days, current_company, current_industry, current_designation,
         current_location, years_of_experience, resume_drive_link, languages_known
       )
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *`,
      [
        full_name, email?.toLowerCase(), phone, linkedin_url,
        current_ctc_fixed ?? null, current_ctc_variable ?? null, current_esops ?? null, expected_ctc ?? null,
        notice_period_days ?? null, current_company ?? null, current_industry ?? null, current_designation ?? null,
        current_location ?? null, years_of_experience ?? null, resume_drive_link ?? null, languages_known ?? null,
      ]
    );
    const candidate = cand.rows[0] as Candidate;

    let application = null;
    if (role_id) {
      const app = await client.query(
        `INSERT INTO applications (candidate_id, role_id, source_channel, agency_id, preferred_location,
           stage, status, recruiter_screening_status, stage_entry_time, sla_hours)
         VALUES ($1,$2,$3,$4,$5,'Applied','Active','New',NOW(),48) RETURNING *`,
        [candidate.id, role_id, source_channel, agency_id || null, preferred_location ?? null]
      );
      application = app.rows[0];

      // Log to activity log
      await client.query(
        `INSERT INTO activity_log (application_id, candidate_id, role_id, event_type, event_detail, new_value, performed_by, performed_by_name)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
        [application.id, candidate.id, role_id, 'Application Created', 'New application created',
         JSON.stringify({ stage: 'Applied', source: source_channel }),
         req.user!.userId, req.user!.name]
      );
    }

    return { candidate, application };
  });

  res.status(201).json(result);
});

// ─── POST /api/candidates/:id/applications — link an existing candidate to a
// role. Fills the gap the manual POST / above can't: that route is
// create-only for the candidate (409s on a duplicate email), so it can't be
// reused for someone who already exists — e.g. a candidate ingested via the
// Job Application Form whose "role applying for" answer didn't match any
// open role (candidateIngest.ts's Unmatched Role — Manual Reconciliation
// path) and needs linking by hand. ────────────────────────────────────────────
router.post('/:id/applications', requireHR, async (req: Request, res: Response) => {
  const { role_id, source_channel } = req.body;

  const candidate = await queryOne<Candidate>('SELECT id FROM candidates WHERE id = $1', [req.params.id]);
  if (!candidate) { res.status(404).json({ error: 'Candidate not found' }); return; }

  if (!role_id) { res.status(400).json({ error: 'role_id is required' }); return; }
  const role = await queryOne<{ id: string }>('SELECT id FROM roles WHERE id = $1', [role_id]);
  if (!role) { res.status(400).json({ error: 'Role not found' }); return; }

  const existingApp = await queryOne<{ id: string }>(
    'SELECT id FROM applications WHERE candidate_id = $1 AND role_id = $2',
    [req.params.id, role_id]
  );
  if (existingApp) {
    res.status(409).json({ error: 'Already linked to this role', application_id: existingApp.id });
    return;
  }

  const application = await transaction(async (client) => {
    const appResult = await client.query(
      `INSERT INTO applications (
         candidate_id, role_id, source_channel,
         stage, status, recruiter_screening_status, stage_entry_time, sla_hours
       ) VALUES ($1,$2,$3,'Applied','Active','New',NOW(),48) RETURNING *`,
      [req.params.id, role_id, source_channel || null]
    );
    const app = appResult.rows[0];

    // Distinguishes the Talent Pool's "Reactivate" action from the original
    // unmatched-role reconciliation flow this route was first built for —
    // both call this same endpoint, so the activity log needs to say which.
    const eventDetail = `Application manually linked${source_channel ? ` (${source_channel})` : ' from unmatched-role reconciliation'}`;

    await client.query(
      `INSERT INTO activity_log (application_id, candidate_id, role_id, event_type, event_detail, new_value, performed_by, performed_by_name)
       VALUES ($1,$2,$3,'Application Created',$4,$5,$6,$7)`,
      [app.id, req.params.id, role_id, eventDetail, JSON.stringify({ stage: 'Applied', source: source_channel }), req.user!.userId, req.user!.name]
    );

    return app;
  });

  res.status(201).json({ application });
});

// ─── PATCH /api/candidates/:id — update profile fields, with edit log ────────
router.patch('/:id', requireHR, async (req: Request, res: Response) => {
  const existing = await queryOne<Candidate>('SELECT * FROM candidates WHERE id = $1', [req.params.id]);
  if (!existing) { res.status(404).json({ error: 'Candidate not found' }); return; }

  const allowedFields = [
    'full_name','email','phone','linkedin_url','parsed_total_yoe',
    'parsed_skills','parsed_industries','parsed_education','job_stability_months',
    'career_progression','parsing_completeness','hr_tags','duplicate_flag',
    'current_ctc_fixed','current_ctc_variable','current_esops','expected_ctc',
    'notice_period_days','current_company','current_industry','current_designation',
    'current_location','years_of_experience','resume_drive_link','languages_known',
  ];

  const updates: string[] = [];
  const values: unknown[] = [];
  const editLogEntries: Array<{ field: string; old: string; new_val: string }> = [];
  let idx = 1;

  for (const field of allowedFields) {
    if (req.body[field] !== undefined) {
      const oldVal = String((existing as unknown as Record<string, unknown>)[field] ?? '');
      const newVal = String(req.body[field]);
      if (oldVal !== newVal) {
        updates.push(`${field} = $${idx++}`);
        values.push(req.body[field]);
        editLogEntries.push({ field, old: oldVal, new_val: newVal });
      }
    }
  }

  if (updates.length === 0) {
    res.json({ candidate: existing, message: 'No changes detected' });
    return;
  }

  values.push(req.params.id);
  const candidate = await transaction(async (client) => {
    const result = await client.query(
      `UPDATE candidates SET ${updates.join(', ')} WHERE id = $${idx} RETURNING *`,
      values
    );

    for (const entry of editLogEntries) {
      await client.query(
        `INSERT INTO candidate_edit_log (candidate_id, field_name, old_value, new_value, changed_by)
         VALUES ($1, $2, $3, $4, $5)`,
        [req.params.id, entry.field, entry.old, entry.new_val, req.user!.userId]
      );
    }

    return result.rows[0] as Candidate;
  });

  res.json({ candidate });
});

// ─── DELETE /api/candidates/:id — remove a candidate with no applications ────
// The one hard delete in this app — every other removal path elsewhere
// (status changes, archival) is deliberately soft. That's safe to
// break from here specifically because a candidate with zero applications
// has no evaluation history or downstream data to lose. Scoped explicitly:
// refuses (409) if the candidate has any application at all, backed up by
// the DB itself — applications.candidate_id has no ON DELETE CASCADE, so a
// candidate with real applications can't be deleted even if this check were
// ever removed or had a bug.
router.delete('/:id', requireHR, async (req: Request, res: Response) => {
  const candidate = await queryOne<{ id: string; full_name: string; email: string | null }>(
    'SELECT id, full_name, email FROM candidates WHERE id = $1', [req.params.id]
  );
  if (!candidate) { res.status(404).json({ error: 'Candidate not found' }); return; }

  const existingApp = await queryOne<{ id: string }>('SELECT id FROM applications WHERE candidate_id = $1', [req.params.id]);
  if (existingApp) {
    res.status(409).json({ error: 'Cannot delete a candidate who has an application on file — only unlinked candidates can be deleted' });
    return;
  }

  // Logged before deleting — activity_log.candidate_id is ON DELETE SET
  // NULL, so this row survives the delete with its candidate_id cleared;
  // the name/email are captured in event_detail so the entry stays
  // readable even once that reference is gone.
  await query(
    `INSERT INTO activity_log (candidate_id, event_type, event_detail, performed_by, performed_by_name)
     VALUES ($1, 'Candidate Deleted', $2, $3, $4)`,
    [candidate.id, `Deleted unlinked candidate ${candidate.full_name}${candidate.email ? ` (${candidate.email})` : ''}`,
     req.user!.userId, req.user!.name]
  );
  await query('DELETE FROM candidates WHERE id = $1', [req.params.id]);
  res.json({ success: true });
});

// ─── GET /api/candidates/:id/edit-log ─────────────────────────────────────────
router.get('/:id/edit-log', async (req: Request, res: Response) => {
  const logs = await query(
    `SELECT el.*, u.name AS changed_by_name
     FROM candidate_edit_log el
     LEFT JOIN users u ON u.id = el.changed_by
     WHERE el.candidate_id = $1
     ORDER BY el.changed_at DESC`,
    [req.params.id]
  );
  res.json({ logs });
});

// ─── GET /api/candidates/:id/activity — full activity timeline ────────────────
router.get('/:id/activity', async (req: Request, res: Response) => {
  const log = await query(
    // COALESCE, not a bare override — see roles.ts's identical GET
    // /:id/activity for the full explanation: al.* already carries the
    // row's own performed_by_name (set at insert time for system-attributed
    // events, e.g. 'System' for ResumeIQ scoring, where performed_by itself
    // is NULL). A bare "u.name AS performed_by_name" let the LEFT JOIN's
    // NULL silently clobber that stored value instead of only filling in
    // the live name for rows that do have a real performed_by.
    `SELECT al.*, COALESCE(u.name, al.performed_by_name) AS performed_by_name, r.title AS role_title
     FROM activity_log al
     LEFT JOIN users u ON u.id = al.performed_by
     LEFT JOIN roles r ON r.id = al.role_id
     WHERE al.candidate_id = $1
     ORDER BY al.created_at DESC`,
    [req.params.id]
  );
  res.json({ activity: log });
});

export default router;
