import { Router, Request, Response } from 'express';
import { query, queryOne, transaction } from '../db/index.js';
import { authenticate, requireHR } from '../middleware/auth.js';
import { Role, AGING_THRESHOLDS, Priority } from '../types/index.js';
import { generateJdContent } from '../services/jdContent.js';
import { renderLongFormJd } from '../services/pdf/longFormJd.js';
import { renderSocialJd } from '../services/pdf/socialJd.js';
import { uploadJdPdf } from '../services/driveService.js';
import { parseRoleFilters, buildRoleFilterSql } from '../utils/roleFilters.js';

const router = Router();
router.use(authenticate);

// ─── Helpers ──────────────────────────────────────────────────────────────────
function computeAging(startDate: string | null, priority: Priority) {
  if (!startDate) return { days_open: 0, aging_alert: 'ok' as const };
  const days = Math.floor((Date.now() - new Date(startDate).getTime()) / 86400000);
  const thresh = AGING_THRESHOLDS[priority] || AGING_THRESHOLDS.P1;
  const aging_alert = days >= thresh.red ? 'red' : days >= thresh.yellow ? 'yellow' : 'ok';
  return { days_open: days, aging_alert };
}

function enrichRole(role: Role) {
  const { days_open, aging_alert } = computeAging(role.start_date || null, role.priority);
  return { ...role, days_open, aging_alert };
}

// ─── GET /api/roles — list all roles with computed fields ─────────────────────
router.get('/', async (req: Request, res: Response) => {
  const filters = parseRoleFilters(req.query as Record<string, unknown>);
  const filterFragment = buildRoleFilterSql(filters, 1);

  const sql = `
    SELECT r.*,
      COUNT(DISTINCT a.id) FILTER (WHERE a.status = 'Active') AS active_candidate_count,
      COUNT(DISTINCT a.id) FILTER (
        WHERE a.status = 'Active'
        AND a.stage IN ('Shortlisted','Interview Round 1','Interview Round 2',
                         'Assignment Round','Founders Round')
      ) AS shortlisted_count
    FROM roles r
    LEFT JOIN applications a ON a.role_id = r.id
    WHERE 1=1
    ${filterFragment.sql}
    GROUP BY r.id ORDER BY r.priority ASC, r.start_date DESC
  `;

  const roles = await query<Role>(sql, filterFragment.params);

  // Strip ctc_band for non-HR/Leadership personas
  const persona = req.user!.persona;
  const result = roles.map(r => {
    const enriched = enrichRole(r);
    if (persona !== 'hr_recruiter' && persona !== 'leadership') {
      const { ctc_band: _ctc, ...safe } = enriched as Role & { ctc_band: string };
      return safe;
    }
    return enriched;
  });

  res.json({ roles: result });
});

// ─── GET /api/roles/filter-options — distinct values for the filter dropdowns ──
// Department + Recruitment Mode are genuinely data-driven (whatever the
// requisition form has actually sent) — Location/Priority/Status are fixed,
// known enums the frontend already hardcodes, so they don't need a round trip.
// Must be registered before GET /:id so "filter-options" isn't swallowed as
// a role id.
router.get('/filter-options', async (_req: Request, res: Response) => {
  const [departments, recruitmentModes] = await Promise.all([
    query<{ department: string }>(
      `SELECT DISTINCT department FROM roles WHERE department IS NOT NULL ORDER BY department`
    ),
    query<{ mode: string }>(
      `SELECT DISTINCT unnest(recruitment_mode) AS mode FROM roles WHERE recruitment_mode IS NOT NULL ORDER BY mode`
    ),
  ]);

  res.json({
    departments:       departments.map(d => d.department),
    recruitment_modes: recruitmentModes.map(r => r.mode),
  });
});

// ─── GET /api/roles/:id — single role detail ──────────────────────────────────
router.get('/:id', async (req: Request, res: Response) => {
  const role = await queryOne<Role>('SELECT * FROM roles WHERE id = $1', [req.params.id]);
  if (!role) { res.status(404).json({ error: 'Role not found' }); return; }

  const persona = req.user!.persona;
  const enriched = enrichRole(role);

  if (persona !== 'hr_recruiter' && persona !== 'leadership') {
    const { ctc_band: _ctc, ...safe } = enriched as Role & { ctc_band: string };
    res.json({ role: safe }); return;
  }
  res.json({ role: enriched });
});

// ─── POST /api/roles — create new role (HR only) ──────────────────────────────
router.post('/', requireHR, async (req: Request, res: Response) => {
  const {
    title, department, hiring_manager_name, priority, new_replacement, replacement_reason,
    num_openings, location, employment_type, yoe_required, ctc_band,
    kpi_expectations, job_description, must_have_skills, nice_to_have_skills,
    suggested_interviewers, assignment_required, recruitment_mode,
    additional_remarks, start_date, target_closure_date,
  } = req.body;

  if (!title || !priority) {
    res.status(400).json({ error: 'title and priority are required' });
    return;
  }

  // ID auto-generated by PostgreSQL sequence (seq_role → R001, R002 …)
  const role = await queryOne<Role>(
    `INSERT INTO roles (
      title, department, hiring_manager_name, priority, new_replacement,
      replacement_reason, num_openings, location, employment_type, yoe_required,
      ctc_band, kpi_expectations, job_description, must_have_skills, nice_to_have_skills,
      suggested_interviewers, assignment_required, recruitment_mode, additional_remarks,
      start_date, target_closure_date, created_by
    ) VALUES (
      $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22
    ) RETURNING *`,
    [
      title, department, hiring_manager_name, priority, new_replacement,
      replacement_reason, num_openings || 1, location, employment_type, yoe_required,
      ctc_band, kpi_expectations, job_description, must_have_skills, nice_to_have_skills,
      suggested_interviewers, assignment_required || false, recruitment_mode || [],
      additional_remarks, start_date, target_closure_date, req.user!.userId,
    ]
  );

  res.status(201).json({ role: enrichRole(role!) });
});

// ─── PATCH /api/roles/:id — update role fields with edit log ─────────────────
router.patch('/:id', requireHR, async (req: Request, res: Response) => {
  const existing = await queryOne<Role>('SELECT * FROM roles WHERE id = $1', [req.params.id]);
  if (!existing) { res.status(404).json({ error: 'Role not found' }); return; }

  const allowedFields = [
    'title','department','hiring_manager_name','priority','status','new_replacement',
    'replacement_reason','num_openings','location','employment_type','yoe_required',
    'ctc_band','kpi_expectations','job_description','must_have_skills','nice_to_have_skills',
    'suggested_interviewers','assignment_required','recruitment_mode','additional_remarks',
    'start_date','target_closure_date','approver_name','approval_date','approval_note',
    'jd_drive_link','social_jd_drive_link','whatsapp_forward_link','referral_message_link',
    'approval_summary_link','posting_status',
  ];

  const updates: string[] = [];
  const values: unknown[] = [];
  const editLogEntries: Array<{ field: string; old: string; new_val: string }> = [];
  let idx = 1;

  for (const field of allowedFields) {
    if (req.body[field] !== undefined) {
      const oldVal = String((existing as unknown as Record<string, unknown>)[field] ?? '');
      const newVal = String(req.body[field]);
      if (oldVal !== newVal) {
        updates.push(`${field} = $${idx++}`);
        values.push(req.body[field]);
        editLogEntries.push({ field, old: oldVal, new_val: newVal });
      }
    }
  }

  if (updates.length === 0) {
    res.json({ role: enrichRole(existing), message: 'No changes detected' });
    return;
  }

  values.push(req.params.id);
  const updatedRole = await transaction(async (client) => {
    const result = await client.query(
      `UPDATE roles SET ${updates.join(', ')} WHERE id = $${idx} RETURNING *`,
      values
    );

    // Write edit log entries
    for (const entry of editLogEntries) {
      await client.query(
        `INSERT INTO role_edit_log (role_id, field_name, old_value, new_value, changed_by)
         VALUES ($1, $2, $3, $4, $5)`,
        [req.params.id, entry.field, entry.old, entry.new_val, req.user!.userId]
      );
    }

    return result.rows[0] as Role;
  });

  // Trigger JD generation when a role transitions into Approved —
  // synchronous (awaited), NOT fire-and-forget. This used to run via
  // setImmediate() after the response was already prepared, which works
  // fine on a persistent server but silently never completes on Vercel:
  // serverless function execution can be frozen/terminated as soon as a
  // response is sent, so a setImmediate() callback scheduled afterward has
  // no guarantee of ever running to completion — confirmed in production,
  // where this left jd_drive_link/social_jd_drive_link permanently null
  // with zero error output. Awaiting it here means the PATCH request takes
  // as long as generation actually takes (~20-30s for a real Claude call +
  // 2 PDF renders + 2 Drive uploads) — see vercel.json's maxDuration, raised
  // to accommodate this. Guarded on the transition itself (not just current
  // status) plus !existing.jd_drive_link, so a role PATCHed with status
  // already 'Approved' (e.g. an unrelated field edit) never regenerates.
  let jdGeneration: { generated: boolean; error?: string } | undefined;
  if (updatedRole.status === 'Approved' && existing.status !== 'Approved' && !existing.jd_drive_link) {
    try {
      const content = await generateJdContent(updatedRole);
      if (!content) {
        console.error(`[JD-Gen] Skipping ${updatedRole.id} — content generation failed`);
        jdGeneration = { generated: false, error: 'JD content generation failed' };
      } else {
        const folderId = process.env.DRIVE_JD_FOLDER_ID;
        if (!folderId) {
          console.error(`[JD-Gen] DRIVE_JD_FOLDER_ID not set — skipping upload for ${updatedRole.id}`);
          jdGeneration = { generated: false, error: 'DRIVE_JD_FOLDER_ID not configured' };
        } else {
          const [longFormBuffer, socialBuffer] = await Promise.all([
            renderLongFormJd(updatedRole, content),
            renderSocialJd(updatedRole, content),
          ]);

          const safeTitle = updatedRole.title.replace(/[^a-zA-Z0-9]+/g, '_');
          const [longFormUpload, socialUpload] = await Promise.all([
            uploadJdPdf(longFormBuffer, `DP_JD_${updatedRole.id}_${safeTitle}.pdf`, folderId),
            uploadJdPdf(socialBuffer, `Social_${updatedRole.id}_${safeTitle}.pdf`, folderId),
          ]);

          // Only write the links once every step above has succeeded — a
          // partial failure leaves both columns untouched so the guard above
          // allows a clean retry on the next role edit. generated_jd_content
          // persists the structured content itself (not just the rendered
          // PDFs) so ResumeIQ can score against it directly instead of
          // re-deriving structure from PDF text later.
          await query(
            'UPDATE roles SET jd_drive_link=$1, social_jd_drive_link=$2, generated_jd_content=$3 WHERE id=$4',
            [longFormUpload.webViewLink, socialUpload.webViewLink, JSON.stringify(content), updatedRole.id]
          );
          await query(
            `INSERT INTO activity_log (role_id, event_type, event_detail, performed_by_name)
             VALUES ($1, 'JD Generated', $2, 'System')`,
            [updatedRole.id, `Long-form + social JD generated for ${updatedRole.title}`]
          );
          console.log(`[JD-Gen] Generated JDs for ${updatedRole.id}`);

          // Reflect the fresh links immediately in this response, rather
          // than making the caller poll for a value that's already known.
          updatedRole.jd_drive_link = longFormUpload.webViewLink;
          updatedRole.social_jd_drive_link = socialUpload.webViewLink;
          updatedRole.generated_jd_content = content as unknown as Record<string, unknown>;
          jdGeneration = { generated: true };
        }
      }
    } catch (err) {
      console.error(`[JD-Gen] Generation failed for ${updatedRole.id}:`, err);
      jdGeneration = { generated: false, error: 'JD generation failed — will retry automatically the next time this role is approved' };
    }
  }

  res.json({ role: enrichRole(updatedRole), jdGeneration });
});

// ─── GET /api/roles/:id/edit-log ──────────────────────────────────────────────
router.get('/:id/edit-log', async (req: Request, res: Response) => {
  const logs = await query(
    `SELECT el.*, u.name AS changed_by_name
     FROM role_edit_log el
     LEFT JOIN users u ON u.id = el.changed_by
     WHERE el.role_id = $1
     ORDER BY el.changed_at DESC`,
    [req.params.id]
  );
  res.json({ logs });
});

// ─── GET /api/roles/:id/pipeline — applications grouped by stage ──────────────
router.get('/:id/pipeline', async (req: Request, res: Response) => {
  const apps = await query(
    `SELECT a.*, c.full_name AS candidate_name, c.email, ag.name AS agency_name
     FROM applications a
     JOIN candidates c ON c.id = a.candidate_id
     LEFT JOIN agencies ag ON ag.id = a.agency_id
     WHERE a.role_id = $1 AND a.status = 'Active'
     ORDER BY a.ai_fit_score DESC NULLS LAST`,
    [req.params.id]
  );

  // Group by stage
  const byStage: Record<string, unknown[]> = {};
  for (const app of apps) {
    const stage = (app as Record<string,unknown>).stage as string;
    if (!byStage[stage]) byStage[stage] = [];
    byStage[stage].push(app);
  }

  res.json({ pipeline: byStage, total: apps.length });
});

export default router;
